const {chromium}=require('playwright'),http=require('http'),fs=require('fs'),path=require('path'),assert=require('assert');
const root=path.join(__dirname,'..'),shots=path.join(__dirname,'qa');fs.mkdirSync(shots,{recursive:true});
const types={'.html':'text/html','.css':'text/css','.js':'application/javascript','.png':'image/png','.svg':'image/svg+xml','.woff':'font/woff'};
const server=http.createServer((req,res)=>{let p=path.join(root,decodeURI(req.url.split('?')[0]==='/'?'/index.html':req.url.split('?')[0]));if(!p.startsWith(root)){res.writeHead(403);res.end();return;}try{res.setHeader('Content-Type',types[path.extname(p)]||'text/plain');res.end(fs.readFileSync(p));}catch(e){res.writeHead(404);res.end();}});
(async()=>{
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const url=`http://127.0.0.1:${server.address().port}`;
 const browser=await chromium.launch({executablePath:process.env.CHROME_PATH,headless:true});
 const page=await browser.newPage({viewport:{width:1440,height:1000}});let errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(url);await page.waitForFunction(()=>document.getElementById('save-status').textContent.includes('salvo'));await page.evaluate(()=>document.fonts.ready);assert(await page.evaluate(()=>document.fonts.check('16px Montserrat')&&document.fonts.check('36px "Playfair Display"')));await page.screenshot({path:path.join(shots,'desktop-inicio.png'),fullPage:true});
 await page.locator('#start').click();await page.locator('#next').click();assert(await page.locator('#error-q1').innerText());
 await page.locator('#q1').fill('Maria Silva');await page.locator('#q3').selectOption('Outro');assert(await page.locator('#q3outro').isVisible());await page.locator('#q3outro').fill('Consultoria');await page.locator('#q3').selectOption('Saúde e Estética');assert(!await page.locator('#q3outro').isVisible());await page.locator('#q4').fill('Serviços de estética');await page.screenshot({path:path.join(shots,'desktop-formulario.png'),fullPage:true});await page.locator('#next').click();
 await page.locator('#back').click();assert.equal(await page.locator('#q1').inputValue(),'Maria Silva');await page.locator('#next').click();await page.locator('#q10').fill('Biomedicina');await page.locator('#next').click();
 await page.locator('input[name=q12][value="Nenhuma"]').check();await page.locator('input[name=q12][value="Instagram"]').check();assert(!await page.locator('input[name=q12][value="Nenhuma"]').isChecked());await page.locator('input[name=q15][value="Sim"]').check();await page.locator('#q15site').fill('https://exemplo.com');await page.locator('input[name=q15][value="Não"]').check();assert(!await page.locator('#q15site').isVisible());await page.locator('#next').click();
 await page.locator('#q19').fill('Mulheres que valorizam segurança e resultados naturais.');await page.locator('#next').click();await page.locator('#attachments').setInputFiles(path.join(root,'assets/logo-fundo-claro.png'));await page.waitForFunction(()=>document.getElementById('file-list').children.length===1);await page.locator('#q23').fill('Berinjela e lilás');await page.locator('#next').click();
 await page.locator('#q26').fill('Estou entrando em uma nova fase profissional.');await page.locator('input[name=q27][value="Fortalecer autoridade"]').check();await page.locator('#next').click();await page.locator('#q35').fill('invalid');await page.locator('#next').click();assert(await page.locator('#error-q35').innerText());await page.locator('#q35').fill('cliente@example.com');await page.locator('#next').click();await page.locator('#q36').fill('Quero organizar meu posicionamento.');await page.locator('#next').click();
 assert(await page.locator('#review').isVisible());assert((await page.locator('#review').innerText()).includes('logo-fundo-claro.png'));await page.getByRole('button',{name:'Editar Seu público e mercado',exact:true}).click();await page.locator('#q19').fill('Perfil revisado de cliente ideal.');await page.locator('#next').click();assert((await page.locator('#review').innerText()).includes('Perfil revisado'));
 await page.locator('#consent').check();await page.locator('#next').click();assert((await page.locator('#form-error').innerText()).includes('ainda não está disponível'));assert(!await page.locator('#success').isVisible());
 await page.reload();await page.locator('#resume').waitFor({state:'visible'});await page.locator('#resume').click();assert((await page.locator('#review').innerText()).includes('logo-fundo-claro.png'));assert((await page.locator('#review').innerText()).includes('Perfil revisado'));
 for(const width of [390,320]){
  await page.setViewportSize({width,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'review overflow '+width);await page.screenshot({path:path.join(shots,`mobile-${width}-revisao.png`)});
  await page.getByRole('button',{name:'Editar Você e seu negócio',exact:true}).click();assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'form overflow '+width);await page.evaluate(()=>window.scrollTo(0,0));await page.waitForTimeout(60);await page.screenshot({path:path.join(shots,`mobile-${width}-formulario.png`),fullPage:true});await page.locator('#next').click();
 }
 await page.evaluate(()=>{
  window.DIAGNOSTICO_RUNTIME.mode='gas';window.mockOutcome='failure';window.google={script:{run:{withSuccessHandler(cb){this.success=cb;return this;},withFailureHandler(cb){this.fail=cb;return this;},submitBriefing(p){window.lastPayload=p;this.success(window.mockOutcome==='success'?{ok:true,receipt:'DDA-TESTE-123'}:{ok:false,message:'Falha simulada. Seu rascunho foi mantido.'});}}}};
 });
 await page.locator('#consent').check();await page.locator('#next').click();assert((await page.locator('#form-error').innerText()).includes('Falha simulada'));assert(await page.evaluate(()=>JSON.parse(localStorage.getItem('thais-diagnostico-v1')).answers.q1==='Maria Silva'));
 await page.evaluate(()=>window.mockOutcome='success');await page.locator('#next').click();await page.locator('#success').waitFor({state:'visible'});assert((await page.locator('#receipt').innerText()).includes('DDA-TESTE-123'));assert(await page.evaluate(()=>Object.keys(JSON.parse(localStorage.getItem('thais-diagnostico-v1')).answers).length===0));assert.equal(await page.locator('#success .whatsapp-contact').getAttribute('href'),'https://wa.me/5531992836383');
 await page.locator('#new-briefing').click();await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(shots,'mobile-inicio.png'),fullPage:true});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'welcome overflow');await page.evaluate(()=>document.documentElement.style.fontSize='32px');assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'200% text overflow');
 assert.deepEqual(errors,[]);console.log('Interface: navegação, campos condicionais, rascunho, anexos, revisão, falha/sucesso e telas 1440/390/320 verificados.');
 await browser.close();server.close();
})().catch(e=>{console.error(e);server.close();process.exit(1);});
